subdir-ccflags-y += -I$(srctree)//drivers/fpga/probe/
subdir-ccflags-y += -I$(srctree)//drivers/net/ethernet/probe/
obj-$(CONFIG_GRIF_PHC) += grif_phc.o

# Enable pr_debug() for all source code file
# ccflags-y += -DDEBUG
