# This Makefile-style file is included by kernel build system Kbuild. It
# describes what modules have to be built and how to build them.

# Drivers to build

ccflags-y += -DFAST_TX_STATUS -DKERNEL_IV_WAR -DRX_SENDUP_SYNC -DDEBUG_FS \
	-DSIF_DSR_WAR -DHAS_INIT_DATA -DHAS_FW -DP2P_CONCURRENT -DESP_USE_SPI

obj-m += esp8089.o
esp8089-objs := esp_debug.o sdio_sif_esp.o spi_sif_esp.o esp_io.o \
	esp_file.o esp_main.o esp_sip.o esp_ext.o esp_ctrl.o \
        esp_mac80211.o esp_debug.o esp_utils.o esp_pm.o testmode.o

# Turn off warning that produces a lot of false-positives. Maybe later we
# should enable it and fix everything it will point us.
subdir-ccflags-y := -Wno-sign-compare
